# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gast < Formula
  desc "GitLab Activity Stream TUI"
  homepage "https://github.com/pataar/gast"
  version "1.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pataar/gast/releases/download/v1.1.2/gast_1.1.2_darwin_amd64.tar.gz"
      sha256 "be0c74ba00aa118b3af70e1813a66983b3784e2e6f6129b9050ef0b21db89908"

      define_method(:install) do
        bin.install "gast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pataar/gast/releases/download/v1.1.2/gast_1.1.2_darwin_arm64.tar.gz"
      sha256 "3d36deb2b408fda64d06c49029609b3a4b2b6e75439a4874b0e62b0fd43c1e36"

      define_method(:install) do
        bin.install "gast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pataar/gast/releases/download/v1.1.2/gast_1.1.2_linux_amd64.tar.gz"
      sha256 "37e6ad487582cf26282074d5dbc3883b9736dec4938fcfb73627788e4b92e30e"
      define_method(:install) do
        bin.install "gast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pataar/gast/releases/download/v1.1.2/gast_1.1.2_linux_arm64.tar.gz"
      sha256 "4ffb3fc4cc4bbec7c0626634b8e87a3948fd7bfdb88429afda1601bd5f74433c"
      define_method(:install) do
        bin.install "gast"
      end
    end
  end
end
