# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gast < Formula
  desc "GitLab Activity Stream TUI"
  homepage "https://github.com/pataar/gast"
  version "1.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/pataar/gast/releases/download/v1.3.0/gast_1.3.0_darwin_amd64.tar.gz"
      sha256 "d2b719fe52d23f842dc8d8693319221b2eeefed22b2a40be960836159a1c2a0e"

      define_method(:install) do
        bin.install "gast"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/pataar/gast/releases/download/v1.3.0/gast_1.3.0_darwin_arm64.tar.gz"
      sha256 "9bdaec67ee31da4c17e7d43e7ffbc797ee87fc19ee402174aa445032ed733e5d"

      define_method(:install) do
        bin.install "gast"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/pataar/gast/releases/download/v1.3.0/gast_1.3.0_linux_amd64.tar.gz"
      sha256 "312ee1c4a89d3f049fc257538497256aa40160ff0776744732a4ed894d87cf1b"
      define_method(:install) do
        bin.install "gast"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/pataar/gast/releases/download/v1.3.0/gast_1.3.0_linux_arm64.tar.gz"
      sha256 "8cc2b71ee62ce873c165849fb2782e6502f060669e516bfa75c221ac85fef798"
      define_method(:install) do
        bin.install "gast"
      end
    end
  end
end
